// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // CLI-only (migrate, validate, db pull, studio). The app's PrismaClient
  // is constructed directly from DATABASE_URL in src/lib/db/prisma.ts and
  // never reads this config, so this must be the direct (non-pooled)
  // connection — migrations must never run over a pooled connection.
  datasource: {
    url: process.env["DIRECT_DATABASE_URL"],
  },
});
